# Disable build scripts except for the packages listed in package.json dependenciesMeta
enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 3d

yarnPath: .yarn/releases/yarn-4.14.1.cjs
